### PR TITLE
Added ability to specify the step action on failure via the emr_action_o...

### PR DESCRIPTION
**Pull request by countrodrigo**
...n_failure option

### CODE REVIEW

**Comment by davidmarin** [comment]
Thanks @countrodrigo. Looking into this! Can you tell me more about your use case?

**Comment by countrodrigo** [comment]
Currently the default behavior is to cancel all queued up steps and wait for new ones to be submitted. We run many independent steps that we queue up on the cluster, and which should continue even if a prior step failed, thus we prefer to specify CONTINUE instead.

**Comment by davidmarin** [comment]
Thanks! That totally makes sense. Will try to slip it into the 0.4.3 release.

By the way, do you have any idea what the difference between `TERMINATE_JOB_FLOW` and `TERMINATE_CLUSTER` is? I haven't been able to find the relevant documentation.

**Comment by davidmarin** [comment]
Never mind found it [here](http://awsdocs.s3.amazonaws.com/ElasticMapReduce/latest/emr-api.pdf): "`TERMINATE_JOB_FLOW` is deprecated, use `TERMINATE_CLUSTER` instead."

**Comment by davidmarin** [comment]
Incorporated this into pull request #976, now awaiting review.

**Pull request closed without merging**
