### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by davidmarin** [comment]
Thanks! Updated [the release checklist](https://github.com/Yelp/mrjob/wiki/Release-Checklist) so that the next release of mrjob will be in wheel form.

**Comment by graingert** [comment]
that makes me wheely happy

**Comment by davidmarin** [comment]
@graingert: v0.4.6 was just released as a wheel.

**Comment by graingert** [comment]
That's wheely good

**Pull request merged**
