### PR TITLE
Add --ssh-socks-proxy

### PR DESCRIPTION
**Pull request by jimjh**
Tests to come after I get some initial feedback!

This adds a `--ssh-socks-proxy` option to set up a SOCKS proxy using `ssh -D`. Note that this does not replace the existing SSH tunnel functionality, since having a `tunnel_url` to query is extremely useful.

### CODE REVIEW

**Comment by mtourne** [comment]
This is awesome! My organization has been needing this for a while.

**Comment by jimjh** [comment]
Why we need this: the current tunnel does not allow the browser to view logs on worker nodes, whereas a SOCKS tunnel provides that _and_ allows us to use other applications such as `ganglia`.

**Comment by davidmarin** [comment]
Can you try something for me? What happens if you run your job with `--ssh-bin 'ssh -D 2001'`? (Replace 2001 with your desired SOCKS proxy port.)

**Comment by jimjh** [comment]
That worked perfectly.

**Pull request closed without merging**
