### PR TITLE
"job key", not "job name"

### PR DESCRIPTION
**Pull request by davidmarin**
mrjob selects a unique key for each job, which is used for selecting temp directories and "locking" for job flow pooling. Because it contains script and user name, it can also be used to audit usage.

This changes the name of the unique key from "job name" (which is easily confused with Hadoop's job names) to "job key". It also removes code which appeared to allow you to set this key manually, but actually does nothing.

See #982 for why this matters.

### CODE REVIEW

**Comment by smallredbean** [comment]
I'm cool with the change. Ship it!

Need a minor version bump, since "--job-name" is removed, right?

**Comment by davidmarin** [comment]
Right, this is for v0.5.0. Thanks!

**Comment by smallredbean** [comment]
SHIP :)

**Comment by davidmarin** [comment]
Also, when I traced through the code, I found `--job-name` didn't actually do anything. :)

**Pull request merged**
