### PR TITLE
Towards Python 2/3 compatibility (take 2)

### PR DESCRIPTION
**Pull request by edschofield**
Here is a set of patches that takes ``mrjob`` a step toward towards Py2/3 compatibility. Python 3 is not yet supported, but the ``diff`` here should be easy to review and take us in the right direction.

### CODE REVIEW

**Comment by msabramo** [comment]
This doesn't merge cleanly anymore. Hopefully the maintainers can try to merge it soon after the conflicts are fixed.

**Comment by edschofield** [comment]
So far the maintainers haven't indicated that they are interested in it. If they do, I will update the patch.

**Comment by davidmarin** [comment]
Thank you! I'd love to see `mrjob` working on Python 3, and this is a step in the right direction.

I'm not going to include this in the 0.4.3 release for fear of breaking things, but we are officially dropping support for Python 2.5 (see #713).

**Comment by davidmarin** [comment]
The 0.4.3 release is all but done, so I'm working on merging your changes for the 0.4.4 release. I'm hoping to have experimental Python 3 support in 0.4.4 (see #217).

**Comment by hayd** [comment]
@ bonitao has a branch on top of this which passes all the tests: https://github.com/bonitao/mrjob/tree/py3

**Comment by davidmarin** [comment]
Neat, took a look. I'm actually most of the way through implementing a solution that doesn't require `six`.

**Comment by davidmarin** [comment]
Rolled this into #1007.

**Pull request closed without merging**
