### PR TITLE
add debug logging for pooling feature

### PR DESCRIPTION
**Pull request by jimjh**
This allows users to identify and troubleshoot pooling issues and control resource usage on EMR.

### CODE REVIEW

**Comment by davidmarin** [comment]
Thanks. Updated your change to use indentation rather than repeating cluster ID, added remaining reasons a cluster could be rejected, and added "OK" when a cluster is accepted.

Also printed the entire, sorted list of usable clusters, and made this a debug log message rather than info.

**Comment by davidmarin** [comment]
Just wanted to let you know that this change has already helped Yelp diagnose a cluster pooling issue. Thanks!

**Comment by jimjh** [comment]
yay!

**Comment by davidmarin** [comment]
Thanks for creating this; it just helped us debug a tricky pooling issue at Yelp. :)

**Pull request merged**
