### PR TITLE
Add cluster info file cache

### PR DESCRIPTION
**Pull request by aaronabf**
Read-through file cache of cluster info to reduce EMR API calls.

### CODE REVIEW

**Comment by davidmarin** [comment]
It looks like you have a serious need to reduce your number of API calls or you wouldn't have built this. Caches are notoriously tricky to get right and I don't really want to be responsible for maintaining such a feature. Let's look at #1990 first?

**Comment by aaronabf** [comment]
So the real reason why I introduced this is due to a new runner I've written, which I wasn't planning to put a revision up for until these precursors were addressed. This new runner bypasses the EMR Step API and schedules directly onto YARN. This allows us to run tons of smaller jobs on a single cluster. In just half an hour I have run over a hundred jobs on just 3 clusters using this runner. A major difficulty we have been facing, and in particular with this runner, is EMR API throttling. This cache was absolutely necessary for this new runner to operate.

**Comment by davidmarin** [comment]
Oh, interesting! If you bypass the EMR API, how does pooling know whether a cluster is free; does the API still report that the cluster is busy even if you didn't launch the job through the API?

Have you tried launching commands via ssh (`ssh ... hadoop jar ...`)?

Also, the way EMR's Hadoop only runs one job at a time is specific to EMR. For example, Google Cloud Dataproc just gives you a Hadoop cluster, and you can run multiple jobs in parallel if you choose.

**Comment by aaronabf** [comment]
Each job declares its expected resource restraints (memory, cores, etc.). Then during pooling we query each valid cluster's YARN resource manager API for various metrics and decide if there is enough room on the cluster for our job. 

> Have you tried launching commands via ssh (ssh ... hadoop jar ...)?

The runner actually does submit the job over ssh via spark-submit.

> Also, the way EMR's Hadoop only runs one job at a time is specific to EMR. 

This is why I call this the "YarnEMRJobRunner". Since our entire infrastructure is on AWS we found this to be a necessity :/

**Comment by davidmarin** [comment]
Closing this for now.

**Pull request closed without merging**
