### PR TITLE
Update hadoop compression options in cookbook

### PR DESCRIPTION
**Pull request by Jyrsa**
The options to pass to jobconf have changed for Hadoop 2. 

Took me a while to puzzle them out on EMR so I thought I'd share while I'm at it.

### CODE REVIEW

**Comment by davidmarin** [comment]
Thanks, but I don't actually any changes; maybe this is the wrong branch?

**Comment by Jyrsa** [comment]
It appears I forgot to push the actual change. I'll fix it tomorrow.

On Wed, 27 Apr 2016, David Marin wrote:

> 
> Thanks, but I don't actually any changes; maybe this is the wrong branch?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[AAlL0k7BKd_alxXhnGhzJycpVXzeIvEoks5p752sgaJpZM4IQ418.gif]
> 
> 
>

-- 
Jyry Suvilehto
+358 50 322 9492

**Comment by Jyrsa** [comment]
How about now?

**Comment by davidmarin** [comment]
I think just using the Hadoop 2 options is fine; mrjob will auto-convert them for Hadoop 1 anyhow. Changing that now.

**Pull request merged**
